<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2019
 *
 * Generated from /var/www/fpptadrupal/sites/default/files/civicrm/ext/com.joineryhq.discountaddlreg/xml/schema/CRM/Discountaddlreg/priceFieldValueDiscount.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:03f220c83949ba1c7a5b626b32e9a223)
 */

/**
 * Database access object for the PriceFieldValueDiscount entity.
 */
class CRM_Discountaddlreg_DAO_PriceFieldValueDiscount extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_price_field_value_discount';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique PriceFieldValueDiscount ID
   *
   * @var int
   */
  public $id;

  /**
   * @var bool
   */
  public $is_active;

  /**
   * FK to Price Field Value
   *
   * @var int
   */
  public $price_field_value_id;

  /**
   * Max dollar amount to discount per person
   *
   * @var float
   */
  public $max_discount_each;

  /**
   * Maximum number of additional participants receiving this discount
   *
   * @var int
   */
  public $max_persons;

  /**
   * FK to Price Field
   *
   * @var int
   */
  public $discount_field_id;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_price_field_value_discount';
    parent::__construct();
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'price_field_value_id', 'civicrm_price_field_value', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'discount_field_id', 'civicrm_price_field', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Discountaddlreg_ExtensionUtil::ts('Unique PriceFieldValueDiscount ID'),
          'required' => TRUE,
          'where' => 'civicrm_price_field_value_discount.id',
          'table_name' => 'civicrm_price_field_value_discount',
          'entity' => 'PriceFieldValueDiscount',
          'bao' => 'CRM_Discountaddlreg_DAO_PriceFieldValueDiscount',
          'localizable' => 0,
        ],
        'is_active' => [
          'name' => 'is_active',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => CRM_Discountaddlreg_ExtensionUtil::ts('Is this discount active?'),
          'required' => TRUE,
          'import' => TRUE,
          'where' => 'civicrm_price_field_value_discount.is_active',
          'export' => TRUE,
          'default' => '0',
          'table_name' => 'civicrm_price_field_value_discount',
          'entity' => 'PriceFieldValueDiscount',
          'bao' => 'CRM_Discountaddlreg_DAO_PriceFieldValueDiscount',
          'localizable' => 0,
        ],
        'price_field_value_id' => [
          'name' => 'price_field_value_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Discountaddlreg_ExtensionUtil::ts('FK to Price Field Value'),
          'where' => 'civicrm_price_field_value_discount.price_field_value_id',
          'table_name' => 'civicrm_price_field_value_discount',
          'entity' => 'PriceFieldValueDiscount',
          'bao' => 'CRM_Discountaddlreg_DAO_PriceFieldValueDiscount',
          'localizable' => 0,
          'FKClassName' => 'CRM_Price_DAO_PriceFieldValue',
        ],
        'max_discount_each' => [
          'name' => 'max_discount_each',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => CRM_Discountaddlreg_ExtensionUtil::ts('Maximum discount per person'),
          'description' => CRM_Discountaddlreg_ExtensionUtil::ts('Max dollar amount to discount per person'),
          'required' => TRUE,
          'precision' => [
            18,
            9,
          ],
          'where' => 'civicrm_price_field_value_discount.max_discount_each',
          'table_name' => 'civicrm_price_field_value_discount',
          'entity' => 'PriceFieldValueDiscount',
          'bao' => 'CRM_Discountaddlreg_DAO_PriceFieldValueDiscount',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
        ],
        'max_persons' => [
          'name' => 'max_persons',
          'type' => CRM_Utils_Type::T_INT,
          'title' => CRM_Discountaddlreg_ExtensionUtil::ts('Maximum discounted participants'),
          'description' => CRM_Discountaddlreg_ExtensionUtil::ts('Maximum number of additional participants receiving this discount'),
          'where' => 'civicrm_price_field_value_discount.max_persons',
          'table_name' => 'civicrm_price_field_value_discount',
          'entity' => 'PriceFieldValueDiscount',
          'bao' => 'CRM_Discountaddlreg_DAO_PriceFieldValueDiscount',
          'localizable' => 0,
        ],
        'discount_field_id' => [
          'name' => 'discount_field_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => CRM_Discountaddlreg_ExtensionUtil::ts('Apply discount in this price field'),
          'description' => CRM_Discountaddlreg_ExtensionUtil::ts('FK to Price Field'),
          'required' => TRUE,
          'where' => 'civicrm_price_field_value_discount.discount_field_id',
          'table_name' => 'civicrm_price_field_value_discount',
          'entity' => 'PriceFieldValueDiscount',
          'bao' => 'CRM_Discountaddlreg_DAO_PriceFieldValueDiscount',
          'localizable' => 0,
          'FKClassName' => 'CRM_Price_DAO_PriceField',
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'price_field_value_discount', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'price_field_value_discount', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
